"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r**v-y61n4bxh+jy#_v8po)e=(lr1nt+mq1_@w-q04nzm^*u(x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow all hosts for development (restrict in production)
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'spectrometric-elva-irremediable.ngrok-free.dev',
    '.ngrok-free.dev',
    '.ngrok.io',
    '*',  # Allow all for development
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    
    # Local apps
    'chat',
]

MIDDLEWARE = [
    # CORS middleware should be at the top
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Check if static directory exists before adding to DIRS
if os.path.exists(BASE_DIR / 'static'):
    STATICFILES_DIRS = [BASE_DIR / 'static']
else:
    STATICFILES_DIRS = []

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'chat.User'

# Login URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ==================== CSRF & CORS CONFIGURATION ====================
# CSRF settings for ngrok and external access
CSRF_TRUSTED_ORIGINS = [
    'https://spectrometric-elva-irremediable.ngrok-free.dev',
    'https://*.ngrok-free.dev',
    'https://*.ngrok.io',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://localhost:8000',
    'https://127.0.0.1:8000',
]

# CORS settings - Allow all origins for development
CORS_ALLOW_ALL_ORIGINS = True  # Set to True for development
CORS_ALLOW_CREDENTIALS = True

# Specific CORS origins (use if CORS_ALLOW_ALL_ORIGINS = False)
CORS_ALLOWED_ORIGINS = [
    'https://spectrometric-elva-irremediable.ngrok-free.dev',
    'https://*.ngrok-free.dev',
    'https://*.ngrok.io',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:3000',  # React/Vue frontend
    'http://127.0.0.1:3000',
]

# CORS methods and headers
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-csrftoken',
    'csrfmiddlewaretoken',
]

# CSRF cookie settings for cross-domain support
CSRF_COOKIE_SAMESITE = 'Lax'  # Change to 'None' if needed for cross-domain
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access CSRF token
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

# Session settings for cross-domain
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# ==================== REST FRAMEWORK CONFIGURATION ====================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    }
}

# ==================== SECURITY SETTINGS ====================
# Security settings for development (disable in production for local testing)
if DEBUG:
    # Disable some security features for easier development
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# ==================== OLLAMA CONFIGURATION ====================
# Ollama API settings
OLLAMA_API_URL = "http://localhost:11434/api"
OLLAMA_TIMEOUT = 300  # 5 minutes timeout for long responses
OLLAMA_DEFAULT_MODEL = "llama2"  # Default model to use

# ==================== MORIO AI ASSISTANT CONFIGURATION ====================
# Morio AI Assistant settings
MORIO_CONFIG = {
    'name': 'Morio',
    'creator': 'BLUE TAIFA',
    'location': 'Kenya',
    'personality': 'helpful, knowledgeable, friendly',
    'expertise': 'technology, African innovation, general knowledge',
    'signature': '— Morio (AI Assistant by BLUE TAIFA)',
}

# ==================== LOGGING CONFIGURATION ====================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'chat': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ==================== FILE UPLOAD SETTINGS ====================
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# ==================== EMAIL CONFIGURATION ====================
# Email configuration (for password reset, etc.)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Print emails to console
DEFAULT_FROM_EMAIL = 'noreply@morio-ai.com'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
EMAIL_USE_TLS = False

# ==================== CACHE CONFIGURATION ====================
# Cache configuration (for faster responses)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Cache timeout for chat responses (seconds)
CHAT_CACHE_TIMEOUT = 3600  # 1 hour

# ==================== AUTO-CONFIGURE FOR NGROK ====================
def auto_configure_ngrok():
    """Automatically add ngrok URL to trusted origins"""
    try:
        import requests
        # Try to get ngrok public URL
        response = requests.get('http://localhost:4040/api/tunnels', timeout=3)
        if response.status_code == 200:
            tunnels = response.json().get('tunnels', [])
            for tunnel in tunnels:
                public_url = tunnel.get('public_url')
                if public_url and public_url not in CSRF_TRUSTED_ORIGINS:
                    CSRF_TRUSTED_ORIGINS.append(public_url)
                    
                    # Extract host from URL
                    from urllib.parse import urlparse
                    parsed = urlparse(public_url)
                    host = parsed.netloc
                    if host not in ALLOWED_HOSTS:
                        ALLOWED_HOSTS.append(host)
                    
                    print(f"[AUTO-CONFIG] Added ngrok URL: {public_url}")
                    print(f"[AUTO-CONFIG] Added host: {host}")
    except:
        # Silently fail if ngrok is not running
        pass

# Run auto-configuration
try:
    auto_configure_ngrok()
except:
    pass

# ==================== DEVELOPMENT/PRODUCTION CHECK ====================
# Detect if running in production
import sys
if 'runserver' not in sys.argv:
    # Production settings
    DEBUG = False
    ALLOWED_HOSTS = [
        'spectrometric-elva-irremediable.ngrok-free.dev',
        '.ngrok-free.dev',
        '.ngrok.io',
        # Add your production domain here
    ]
    
    # Security settings for production
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Static files in production
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    
    # Database configuration for production (example for PostgreSQL)
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.postgresql',
    #         'NAME': 'your_db_name',
    #         'USER': 'your_db_user',
    #         'PASSWORD': 'your_db_password',
    #         'HOST': 'localhost',
    #         'PORT': '5432',
    #     }
    # }

print(f"[SETTINGS] DEBUG mode: {DEBUG}")
print(f"[SETTINGS] ALLOWED_HOSTS: {ALLOWED_HOSTS}")
print(f"[SETTINGS] CSRF_TRUSTED_ORIGINS: {CSRF_TRUSTED_ORIGINS}")
print(f"[SETTINGS] CORS_ALLOW_ALL_ORIGINS: {CORS_ALLOW_ALL_ORIGINS}")