# Generated by Django 4.2.25 on 2026-01-27 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_name', models.CharField(default='', help_text='Name of your AI assistant', max_length=100)),
                ('company_name', models.CharField(default='', help_text='Company this AI represents', max_length=200)),
                ('location', models.CharField(default='', help_text='Location/office of the company', max_length=200)),
                ('base_model', models.CharField(default='phi', help_text='Ollama base model name', max_length=100)),
                ('role_description', models.TextField(default='customer assistant', help_text="Brief description of the AI's role")),
                ('greeting_message', models.TextField(default="Hi there! I'm {ai_name}, your assistant for {company_name} in {location}! How can I help you today?", help_text='Use {ai_name}, {company_name}, {location} as placeholders')),
                ('use_rag', models.BooleanField(default=True, help_text='Enable RAG for document-based responses')),
                ('rag_threshold', models.FloatField(default=0.7, help_text='Similarity threshold for RAG retrieval')),
                ('max_context_length', models.IntegerField(default=2000, help_text='Max context length for responses')),
                ('system_prompt_template', models.TextField(default='ROLE: You are {ai_name}, an {role_description} for {company_name} in {location}\n\nPERSONALITY: You are helpful, friendly, and professional. You provide accurate information and excellent customer service.\n\nRULES:\n1. Your name is ALWAYS {ai_name}\n2. You work for {company_name} in {location}\n3. ALWAYS introduce yourself as: "{greeting_message}"\n4. If you don\'t know something, say so and offer to help find the answer\n5. Always be polite and professional\n6. Use relevant information from provided context when available\n7. Keep responses concise and helpful', help_text='System prompt template for Ollama')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('document_type', models.CharField(choices=[('faq', 'FAQ'), ('policy', 'Company Policy'), ('product', 'Product Info'), ('service', 'Service Info'), ('employee', 'Employee Info'), ('other', 'Other')], default='faq', max_length=20)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('embeddings_data', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='RAG.aiconfiguration')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('relevant_docs_ids', models.CharField(blank=True, default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ai_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='RAG.aiconfiguration')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='RAG_convers_session_084150_idx'), models.Index(fields=['ai_config'], name='RAG_convers_ai_conf_7f4ffc_idx')],
            },
        ),
    ]
